services:
  - type: web
    name: lead-style-app
    env: node
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: leadStyleDB
          property: connectionString

databases:
  - name: leadStyleDB
    databaseName: leadstyleapp_prod
    user: leadstyle